(()=>{
'use strict';
let lastPlayers=[];
function sock(){return window.__MORG_SOCKET__||window.socket||null}
function me(){const s=sock();return String(window.myId||s?.id||'')}
function request(id,b){const s=sock();if(!s||!id||String(id)===me())return;s.emit('requestGame',{targetId:String(id)});if(b){b.disabled=true;b.textContent='📨 ارسال شد';setTimeout(()=>{if(b.isConnected){b.disabled=false;b.textContent='🎮 درخواست بازی'}},1600)}}
const css=`#morg-online-fab{position:fixed;right:22px;top:110px;z-index:99998;background:#8e44ad;color:#fff;border:0;border-radius:22px;padding:11px 16px;font-weight:800;box-shadow:0 5px 0 #633178;cursor:pointer}#morg-online-panel{position:fixed;right:22px;top:165px;width:360px;max-width:calc(100vw - 30px);max-height:70vh;background:#fff7e5;border:3px solid #f0a23a;border-radius:24px;z-index:99999;box-shadow:0 15px 45px #0008;overflow:hidden;direction:rtl}#morg-online-head{height:52px;background:linear-gradient(135deg,#6b351e,#9b5428);color:#fff;padding:0 12px;display:flex;align-items:center;justify-content:space-between;cursor:move;touch-action:none}#morg-online-head b{font-size:16px}#morg-online-close{border:0;background:#c0392b;color:#fff;width:34px;height:34px;border-radius:50%;font-size:20px;font-weight:900;cursor:pointer}#morg-online-list{padding:10px;overflow-y:auto;max-height:calc(70vh - 52px)}.morg-online-row{background:#fff;border:2px solid #f0a23a;border-radius:17px;padding:10px;margin-bottom:8px;display:flex;align-items:center;gap:8px}.morg-online-info{flex:1;min-width:0}.morg-online-name{font-weight:900;color:#6b351e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.morg-online-status{font-size:12px;color:#777;margin-top:3px}.morg-online-request{border:0;border-radius:14px;background:#27ae60;color:#fff;padding:8px 10px;font-weight:800;cursor:pointer;white-space:nowrap}.morg-online-request:disabled{opacity:.7}.morg-empty{text-align:center;padding:25px;color:#777}@media(max-width:600px){#morg-online-fab{right:10px;top:80px}#morg-online-panel{right:10px;top:130px;width:calc(100vw - 20px)}}`;
function style(){if(document.getElementById('morg-online-style'))return;const s=document.createElement('style');s.id='morg-online-style';s.textContent=css;document.head.appendChild(s)}
function render(){
 style();
 let fab=document.getElementById('morg-online-fab');
 if(!fab){fab=document.createElement('button');fab.id='morg-online-fab';fab.textContent='👥 بازیکنان آنلاین';fab.onclick=()=>{const p=document.getElementById('morg-online-panel');if(p)p.style.display='block'};document.body.appendChild(fab)}
 let panel=document.getElementById('morg-online-panel');
 if(!panel){panel=document.createElement('div');panel.id='morg-online-panel';panel.innerHTML='<div id="morg-online-head"><b>👥 بازیکنان آنلاین</b><button id="morg-online-close" type="button">×</button></div><div id="morg-online-list"></div>';document.body.appendChild(panel);panel.querySelector('#morg-online-close').onclick=()=>panel.style.display='none';makeDraggable(panel,panel.querySelector('#morg-online-head'))}
 const list=panel.querySelector('#morg-online-list');const others=lastPlayers.filter(p=>p?.id&&String(p.id)!==me());list.innerHTML='';
 if(!others.length){list.innerHTML='<div class="morg-empty">بازیکن آنلاین دیگری نیست</div>';return}
 others.forEach(p=>{const row=document.createElement('div');row.className='morg-online-row';const info=document.createElement('div');info.className='morg-online-info';info.innerHTML='<div class="morg-online-name">'+esc(p.avatar||'🐔')+' '+esc(p.name||'بازیکن')+'</div><div class="morg-online-status">'+esc(statusText(p.status))+'</div>';const b=document.createElement('button');b.className='morg-online-request';b.type='button';b.textContent='🎮 درخواست بازی';b.onclick=()=>request(p.id,b);row.append(info,b);list.appendChild(row)})
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusText(s){return ({ready:'آماده',requesting:'در انتظار پاسخ',requested:'درخواست جدید',room:'داخل اتاق',playing:'در حال بازی',watching:'در حال تماشا'}[s]||'آنلاین')}
function makeDraggable(el,handle){let sx=0,sy=0,ox=0,oy=0,drag=false;const start=(x,y)=>{const r=el.getBoundingClientRect();sx=x;sy=y;ox=r.left;oy=r.top;drag=true;el.style.left=ox+'px';el.style.top=oy+'px';el.style.right='auto'};const move=(x,y)=>{if(!drag)return;let nx=ox+x-sx,ny=oy+y-sy;nx=Math.max(5,Math.min(window.innerWidth-el.offsetWidth-5,nx));ny=Math.max(5,Math.min(window.innerHeight-el.offsetHeight-5,ny));el.style.left=nx+'px';el.style.top=ny+'px'};const end=()=>drag=false;handle.addEventListener('pointerdown',e=>{if(e.target.id==='morg-online-close')return;handle.setPointerCapture?.(e.pointerId);start(e.clientX,e.clientY)});handle.addEventListener('pointermove',e=>move(e.clientX,e.clientY));handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end)}
function hook(){const s=sock();if(s&&!s.__morgForceRequest2){s.__morgForceRequest2=true;s.on('playerListUpdate',l=>{lastPlayers=Array.isArray(l)?l:[];render()});s.on('connect',()=>{if(s.id)window.myId=s.id;render()});s.on('hello',d=>{if(d?.id)window.myId=d.id;render()})}if(s?.id)window.myId=s.id;render()}
hook();setInterval(hook,1000);
})();