(()=>{
'use strict';
if(window.__MORG_QUICK_READY)return;window.__MORG_QUICK_READY=1;
const css=`#mq-panel{position:fixed;inset:0;z-index:2147483005;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.72);font-family:Tahoma,Arial;direction:rtl}#mq-box{width:min(520px,92vw);background:linear-gradient(145deg,#fff7df,#f0d29b);border:4px solid #c86d22;border-radius:28px;padding:22px;text-align:center;box-shadow:0 25px 70px #0009}#mq-box h2{margin:4px 0 18px;color:#8b3f12}#mq-counts{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}#mq-counts button,#mq-cancel{border:0;border-radius:14px;padding:12px;background:#f3a33d;color:#3b1908;font-weight:900;font-size:17px;cursor:pointer;box-shadow:0 4px 0 #a85d16}#mq-cancel{margin-top:18px;background:#c94b3d;color:#fff}#mq-search{display:none}#mq-spin{font-size:58px;animation:mqspin 1s linear infinite}@keyframes mqspin{to{transform:rotate(360deg)}}#mq-vs{display:none;position:fixed;inset:0;z-index:2147483006;background:linear-gradient(135deg,#17100b,#6d3515);color:#fff;align-items:center;justify-content:center;font-family:Tahoma;direction:rtl}#mq-vbox{text-align:center;width:min(900px,94vw)}#mq-vbox h1{font-size:42px;margin:0 0 18px}#mq-players{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:12px}.mq-player{background:#fff1d0;color:#54240d;border-radius:18px;padding:18px;font-weight:900;border:3px solid #e2a23f}.mq-num{font-size:58px;font-weight:900;margin:18px}`;const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
const panel=document.createElement('div');panel.id='mq-panel';panel.innerHTML=`<div id="mq-box"><h2>⚡ بازی سریع</h2><p id="mq-title">تعداد بازیکنان را انتخاب کن</p><div id="mq-counts">${[2,3,4,5,6,7,8,9,10,12,15,20].map(n=>`<button data-n="${n}">${n}</button>`).join('')}</div><div id="mq-search"><div id="mq-spin">🔎</div><h2>در حال جستجوی حریف...</h2><p id="mq-search-txt"></p></div><button id="mq-cancel">لغو</button></div>`;document.body.appendChild(panel);
const vs=document.createElement('div');vs.id='mq-vs';vs.innerHTML=`<div id="mq-vbox"><h1>⚔️ VS</h1><div id="mq-players"></div><div class="mq-num" id="mq-num">5</div><p>بازی تا چند لحظه دیگر شروع می‌شود...</p></div>`;document.body.appendChild(vs);
const socket=()=>window.__MORG_SOCKET__||window.socket||window.io?.();
function showSearch(n){document.getElementById('mq-counts').style.display='none';document.getElementById('mq-search').style.display='block';document.getElementById('mq-title').textContent='انتظار برای بازیکنان';document.getElementById('mq-search-txt').textContent=`جستجو برای بازی ${n} نفره`;}
function open(){panel.style.display='flex'}
function close(){panel.style.display='none'}
function showVS(players){close();vs.style.display='flex';const box=document.getElementById('mq-players');box.innerHTML=(players||[]).map((p,i)=>`<div class="mq-player">🐔<br>${String(p?.name||p?.username||p||'بازیکن '+(i+1))}</div>`).join('');let n=5;document.getElementById('mq-num').textContent=n;const t=setInterval(()=>{n--;document.getElementById('mq-num').textContent=n;if(n<=0){clearInterval(t);setTimeout(()=>vs.style.display='none',500)}},1000)}
document.addEventListener('click',e=>{const q=e.target.closest('[data-action="quick-game"],#quickGameBtn,[data-quick-game]');if(q){e.preventDefault();open();}const b=e.target.closest('#mq-counts button');if(b){const n=+b.dataset.n;showSearch(n);const so=socket();if(so)so.emit('quickGame',{playerCount:n});}if(e.target.id==='mq-cancel'){const so=socket();if(so)so.emit('cancelQuickGame');document.getElementById('mq-counts').style.display='grid';document.getElementById('mq-search').style.display='none';document.getElementById('mq-title').textContent='تعداد بازیکنان را انتخاب کن';if(!e.target.closest('#mq-box'))close();}});
const so=socket();if(so){so.on('quickGameFound',d=>showVS(d?.players||d?.room?.players||[]));so.on('friendGameFound',d=>showVS(d?.players||d?.room?.players||[]));so.on('quickGameCancelled',close);so.on('quickGameError',x=>{close();alert(x?.message||x||'خطا در بازی سریع')});}
window.MorgdoniQuick={open,showVS};
})();