(()=>{
'use strict';
if(window.__MORG_QUICK_READY)return;window.__MORG_QUICK_READY=true;
const css=`#mq-panel{position:fixed;inset:0;z-index:2147483005;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.78);backdrop-filter:blur(8px);font-family:Tahoma,Arial;direction:rtl}#mq-box{width:min(560px,94vw);background:linear-gradient(145deg,#fff7df,#efd09b);border:4px solid #c86d22;border-radius:28px;padding:24px;text-align:center;color:#54240d;box-shadow:0 25px 80px #000b}#mq-counts{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}#mq-counts button,#mq-cancel{border:0;border-radius:14px;padding:12px;background:#f3a33d;color:#3b1908;font-weight:900;font-size:17px;cursor:pointer;box-shadow:0 4px 0 #a85d16}#mq-cancel{margin-top:18px;background:#c94b3d;color:#fff}#mq-search{display:none}.mq-spin{font-size:64px;animation:mqspin 1s linear infinite}@keyframes mqspin{to{transform:rotate(360deg)}}#mq-vs{display:none;position:fixed;inset:0;z-index:2147483006;background:linear-gradient(135deg,#170e08,#6d3515);color:#fff;align-items:center;justify-content:center;font-family:Tahoma;direction:rtl}#mq-vbox{text-align:center;width:min(950px,94vw)}#mq-vbox h1{font-size:46px;margin:0 0 18px}.mq-players{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:12px}.mq-player{background:#fff1d0;color:#54240d;border-radius:18px;padding:18px;font-weight:900;border:3px solid #e2a23f}.mq-num{font-size:64px;font-weight:900;margin:18px;color:#ffd45a}@media(max-width:600px){#mq-counts{grid-template-columns:repeat(3,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const panel=document.createElement('div');panel.id='mq-panel';panel.innerHTML=`<div id="mq-box"><h2>⚡ بازی سریع</h2><p id="mq-title">تعداد بازیکنان را انتخاب کن</p><div id="mq-counts">${[2,3,4,5,6,7,8,9,10,12,15,20].map(n=>`<button data-mq-count="${n}">${n} نفر</button>`).join('')}</div><div id="mq-search"><div class="mq-spin">🔎</div><h2>در حال جستجوی حریف...</h2><p id="mq-search-text"></p></div><button id="mq-cancel">❌ لغو</button></div>`;document.body.appendChild(panel);
const vs=document.createElement('div');vs.id='mq-vs';vs.innerHTML=`<div id="mq-vbox"><h1>⚔️ VS</h1><div id="mq-players" class="mq-players"></div><div id="mq-num" class="mq-num">5</div><p>بازی تا چند لحظه دیگر شروع می‌شود...</p></div>`;document.body.appendChild(vs);
let bound=null,vsTimer=null;
const getSocket=()=>window.__MORG_SOCKET__||window.socket||null;
function bind(){const s=getSocket();if(!s||s===bound)return;if(bound)return;bound=s;s.on('quickGameFound',d=>showVS(d?.players||d?.room?.players||[]));s.on('friendGameFound',d=>showVS(d?.players||d?.room?.players||[]));s.on('quickGameCancelled',()=>reset(true));s.on('quickGameError',m=>{reset(true);alert(m?.message||m||'خطا در بازی سریع')})}
function open(){panel.style.display='flex';bind()}
function reset(hide){$('mq-counts').style.display='grid';$('mq-search').style.display='none';$('mq-title').textContent='تعداد بازیکنان را انتخاب کن';if(hide)panel.style.display='none'}
function $(id){return document.getElementById(id)}
function search(n){$('mq-counts').style.display='none';$('mq-search').style.display='block';$('mq-title').textContent='انتظار برای بازیکنان';$('mq-search-text').textContent=`جستجو برای بازی ${n} نفره`;bind();const s=getSocket();if(s)s.emit('quickGame',{playerCount:n});else alert('اتصال به سرور برقرار نیست')}
function showVS(players){reset(true);vs.style.display='flex';$('mq-players').innerHTML=(players||[]).map((p,i)=>`<div class="mq-player">🐔<br>${esc(p?.name||p?.username||p||'بازیکن '+(i+1))}</div>`).join('');let n=5;$('mq-num').textContent=n;clearInterval(vsTimer);vsTimer=setInterval(()=>{n--;$('mq-num').textContent=Math.max(0,n);if(n<=0){clearInterval(vsTimer);setTimeout(()=>vs.style.display='none',450)}},1000)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('click',e=>{const q=e.target.closest('#quickGameBtn,[data-action="quick-game"],[data-quick-game]');if(q){e.preventDefault();open();return}const b=e.target.closest('[data-mq-count]');if(b){search(+b.dataset.mqCount);return}if(e.target.closest('#mq-cancel')){const s=getSocket();if(s)s.emit('cancelQuickGame');reset(true)}});
setInterval(bind,250);bind();window.MorgdoniQuick={open,showVS};
})();