(()=>{
const style=document.createElement('style');style.textContent=`#morgReq{position:static!important;right:auto!important;bottom:auto!important;width:100%;max-width:none;margin:12px 0;background:#fff7e5;border:2px solid #d47a2a;border-radius:24px;padding:14px;box-shadow:0 6px 18px #0003;font-family:Segoe UI,Tahoma,sans-serif;direction:rtl}#morgReq h3{margin:0 0 10px;color:#7b3f00}#morgReq button{border:0;border-radius:18px;padding:9px 14px;margin:4px;font-weight:bold;cursor:pointer}.rq{background:#27ae60;color:#fff}.rr{background:#c0392b;color:#fff}.rw{background:#8e44ad;color:#fff}.rp{background:#ffa047}.morgPlayer{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #ead5b0}`;document.head.appendChild(style);
let box=document.createElement('div');box.id='morgReq';
function mount(){if(document.getElementById('morgReq'))return;const host=document.querySelector('#lobby,#lobbyPanel,.lobby,.lobby-panel,[data-lobby],.join-panel')||document.querySelector('main')||document.body;host.appendChild(box)}
mount();setTimeout(mount,500);setTimeout(mount,1500);
let pending=null;const sock=()=>window.__MORG_SOCKET__;function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function showRequest(d){pending=d;box.innerHTML=`<h3>📨 درخواست بازی</h3><div><b>${esc(d?.fromName||'بازیکن')}</b> می‌خواهد با شما بازی کند.</div><button class="rq" id="rqYes">قبول</button><button class="rr" id="rqNo">رد</button>`;document.getElementById('rqYes').onclick=()=>{sock()?.emit('acceptGame',{fromId:d.fromId});pending=null;box.innerHTML='<h3>⏳ درخواست قبول شد</h3><div>در حال آماده‌سازی بازی...</div>';};document.getElementById('rqNo').onclick=()=>{sock()?.emit('rejectGame',{fromId:d.fromId});pending=null;render();};}
function showChoice(d){const fromId=d?.fromId,name=d?.fromName||'بازیکن';box.innerHTML=`<h3>🎮 ${esc(name)} وارد بازی شما می‌شود</h3><div>انتخاب کنید:</div><button class="rq" id="joinBtn">🎮 جوین</button><button class="rw" id="watchBtn">👀 تماشا</button>`;document.getElementById('joinBtn').onclick=()=>{sock()?.emit('chooseGameOption',{fromId,option:'join'});box.innerHTML='<h3>✅ جوین شد</h3>';};document.getElementById('watchBtn').onclick=()=>{sock()?.emit('chooseGameOption',{fromId,option:'watch'});box.innerHTML='<h3>👀 تماشاچی شد</h3>';};}
function render(list=[]){box.innerHTML='<h3>👥 بازیکنان آنلاین</h3><div id="morgPlayers"></div>';const p=document.getElementById('morgPlayers');list.filter(x=>x.id!==sock()?.id).forEach(x=>{const row=document.createElement('div');row.className='morgPlayer';row.innerHTML=`<span>${x.avatar||'🐔'} ${esc(x.name)} <small>(${esc(x.status||'آماده')})</small></span><button class="rp">درخواست بازی</button>`;row.querySelector('button').onclick=()=>sock()?.emit('requestGame',{targetId:x.id});p.appendChild(row);});}
let tries=0;function hook(){const s=sock();if(!s){if(tries++<100)setTimeout(hook,200);return;}s.on('playerListUpdate',render);s.on('gameRequest',showRequest);s.on('busyGameChoice',showChoice);s.on('gameAccepted',showChoice);s.on('gameRejected',d=>alert('درخواست رد شد توسط '+(d?.byName||'بازیکن')));s.on('gameRequestError',d=>alert(d||'ارسال درخواست ممکن نشد'));s.on('gameError',d=>alert(d||'خطای بازی'));s.on('registrationSuccess',()=>s.emit('getPlayerList'));s.emit('getPlayerList')}hook();
})();
