(()=>{
  const style=document.createElement('style');style.textContent=`#morgReq{position:fixed;right:16px;bottom:16px;z-index:99999;background:#fff7e5;border:3px solid #d47a2a;border-radius:24px;padding:14px;box-shadow:0 12px 35px #0008;max-width:360px;font-family:Segoe UI,Tahoma,sans-serif;direction:rtl}#morgReq h3{margin:0 0 10px;color:#7b3f00}#morgReq button{border:0;border-radius:18px;padding:9px 14px;margin:4px;font-weight:bold;cursor:pointer}.rq{background:#27ae60;color:#fff}.rr{background:#c0392b;color:#fff}.rw{background:#8e44ad;color:#fff}.rp{background:#ffa047}.morgPlayer{display:flex;align-items:center;gap:8px;padding:6px 0;border-bottom:1px solid #ead5b0}.morgPlayer button{padding:6px 10px}`;document.head.appendChild(style);
  let box=document.createElement('div');box.id='morgReq';box.innerHTML='<h3>👥 بازیکنان آنلاین</h3><div id="morgPlayers">در حال اتصال...</div>';document.body.appendChild(box);
  const players=document.getElementById('morgPlayers');let pending=null;
  function showRequest(d){pending=d;box.innerHTML=`<h3>📨 درخواست بازی</h3><div><b>${esc(d?.fromName||'بازیکن')}</b> می‌خواهد با شما بازی کند.</div><button class="rq" id="rqYes">قبول</button><button class="rr" id="rqNo">رد</button>`;document.getElementById('rqYes').onclick=()=>{window.__MORG_SOCKET__?.emit('acceptGame',{fromId:d.fromId});pending=null;};document.getElementById('rqNo').onclick=()=>{window.__MORG_SOCKET__?.emit('rejectGame',{fromId:d.fromId});pending=null;render();};}
  function render(list=[]){box.innerHTML='<h3>👥 بازیکنان آنلاین</h3><div id="morgPlayers"></div>';const p=document.getElementById('morgPlayers');list.filter(x=>x.status==='ready'||x.status==='playing'||x.status==='requesting').forEach(x=>{const row=document.createElement('div');row.className='morgPlayer';row.innerHTML=`<span>${x.avatar||'🐔'} ${esc(x.name)}</span><button class="rp">درخواست بازی</button>`;row.querySelector('button').onclick=()=>{window.__MORG_SOCKET__?.emit('requestGame',{targetId:x.id});};p.appendChild(row)});}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  let tries=0;function hook(){const s=window.__MORG_SOCKET__;if(!s){if(tries++<50)setTimeout(hook,200);return;}s.on('playerListUpdate',render);s.on('gameRequest',showRequest);s.on('gameRejected',d=>alert('درخواست رد شد توسط '+(d?.byName||'بازیکن')));s.on('gameRequestError',d=>alert(d||'ارسال درخواست ممکن نشد'));s.on('registrationSuccess',()=>s.emit('getPlayerList'));s.emit('getPlayerList');}hook();
})();
