(()=>{
'use strict';
const KEY='morgdoni_shop_v1';
const DEFAULT={coins:0,lastDaily:'',streak:0,owned:[]};
const ITEMS=[
{id:'frame-gold',name:'قاب طلایی',icon:'🖼️',price:500},
{id:'back-royal',name:'پشت کارت سلطنتی',icon:'🃏',price:700},
{id:'win-fire',name:'افکت برد آتشین',icon:'🔥',price:900},
{id:'avatar-fox',name:'آواتار روباه',icon:'🦊',price:350},
{id:'emoji-star',name:'واکنش ویژه ⭐',icon:'⭐',price:250}
];
function load(){try{return Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {...DEFAULT}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));return s}
function today(){return new Date().toISOString().slice(0,10)}
function daily(s){const t=today();if(s.lastDaily===t)return false;const y=new Date();y.setDate(y.getDate()-1);const yd=y.toISOString().slice(0,10);s.streak=s.lastDaily===yd?(s.streak||0)+1:1;const reward=100+Math.min(200,(s.streak-1)*25);s.coins=(s.coins||0)+reward;s.lastDaily=t;save(s);return reward}
function css(){if(document.getElementById('md-shop-css'))return;const x=document.createElement('style');x.id='md-shop-css';x.textContent=`#md-shop-fab{position:fixed;left:18px;bottom:18px;z-index:9998;background:#27ae60;color:#fff;border:0;border-radius:50px;padding:13px 20px;font-weight:900;box-shadow:0 5px 0 #176b3b;cursor:pointer}#md-shop-modal{position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:18px}#md-shop-box{width:min(680px,95vw);max-height:88vh;overflow:auto;background:#fef7e6;border:4px solid #d47a2a;border-radius:38px;padding:24px;color:#4b2b12;font-family:Tahoma,Arial,sans-serif}#md-shop-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:15px}#md-shop-head h2{color:#d47a2a;margin:0}#md-coins{background:#ffecb3;border-radius:30px;padding:10px 15px;font-weight:900}#md-daily{background:#fff4cf;border:2px solid #f2b84b;border-radius:25px;padding:15px;margin-bottom:16px;text-align:center}.md-item{display:flex;align-items:center;justify-content:space-between;gap:10px;background:#fff;border:2px solid #f2c27b;border-radius:22px;padding:12px;margin:9px 0}.md-item .ic{font-size:30px}.md-item button{border:0;border-radius:22px;padding:9px 15px;background:#27ae60;color:white;font-weight:900;cursor:pointer}.md-item button:disabled{background:#999;cursor:default}#md-shop-close{background:#c0392b;color:#fff;border:0;border-radius:20px;padding:8px 14px;font-weight:900;cursor:pointer}`;document.head.appendChild(x)}
function render(){css();let s=load();let r=document.getElementById('md-shop-modal');if(r)r.remove();r=document.createElement('div');r.id='md-shop-modal';r.innerHTML=`<div id="md-shop-box"><div id="md-shop-head"><h2>🛒 فروشگاه مرغ‌دونی</h2><div id="md-coins">🪙 ${s.coins} سکه</div></div><div id="md-daily">🎁 جایزه روزانه<br><b>هر روز حداقل ۱۰۰ سکه</b><br><small>روز پشت‌سرهم: ${s.streak||0}</small><br><button id="md-claim" class="md-item" style="margin:10px auto 0;border:0;background:#27ae60;color:#fff;padding:10px 18px;border-radius:22px;font-weight:900;cursor:pointer">دریافت جایزه امروز</button></div><h3>🛍️ آیتم‌ها</h3><div id="md-items"></div><button id="md-shop-close">بستن</button></div>`;document.body.appendChild(r);const claim=r.querySelector('#md-claim');if(s.lastDaily===today()){claim.textContent='✅ جایزه امروز دریافت شده';claim.disabled=true}else claim.onclick=()=>{const reward=daily(load());claim.textContent=`🎉 ${reward} سکه گرفتی!`;claim.disabled=true;render()};const box=r.querySelector('#md-items');ITEMS.forEach(it=>{const owned=s.owned.includes(it.id);const d=document.createElement('div');d.className='md-item';d.innerHTML=`<div><span class="ic">${it.icon}</span> <b>${it.name}</b></div><button ${owned?'disabled':''}>${owned?'✅ خریداری شده':'🪙 '+it.price}</button>`;d.querySelector('button').onclick=()=>{const q=load();if(q.coins<it.price){alert('🪙 سکه کافی نداری.');return}q.coins-=it.price;q.owned.push(it.id);save(q);render()};box.appendChild(d)});r.querySelector('#md-shop-close').onclick=()=>r.remove();r.onclick=e=>{if(e.target===r)r.remove()}}
function boot(){css();if(document.getElementById('md-shop-fab'))return;const b=document.createElement('button');b.id='md-shop-fab';b.textContent='🛒 فروشگاه | 🪙 '+load().coins;b.onclick=render;document.body.appendChild(b);const reward=daily(load());if(reward){setTimeout(()=>alert(`🎁 جایزه روزانه مرغ‌دونی!\n🪙 ${reward} سکه دریافت کردی.`),700)} }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.MorgdoniShop={open:render,load};
})();
