const SOCKET_SHIM = `class MorgdoniSocket{constructor(){this.events={};this.id=null;this.queue=[];const p=location.protocol==='https:'?'wss:':'ws:';this.ws=new WebSocket(p+'//'+location.host+'/ws');this.ws.onopen=()=>{this.emitLocal('connect');for(const m of this.queue)this.ws.send(m);this.queue=[]};this.ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m?.type)this.emitLocal(m.type,m.data)}catch{}};this.ws.onclose=()=>this.emitLocal('disconnect');this.ws.onerror=e=>this.emitLocal('connect_error',e)}on(e,c){(this.events[e]??=[]).push(c);return this}once(e,c){const f=d=>{this.off(e,f);c(d)};return this.on(e,f)}off(e,c){this.events[e]=(this.events[e]||[]).filter(x=>x!==c);return this}emit(e,d){const m=JSON.stringify({type:e,data:d??null});if(this.ws.readyState===1)this.ws.send(m);else this.queue.push(m);return this}emitLocal(e,d){for(const c of this.events[e]||[])try{c(d)}catch(x){console.error(x)}}disconnect(){this.ws?.close()}}window.io=window.io||function(){const s=new MorgdoniSocket();window.__MORG_SOCKET__=s;return s};`;

function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createDeck(){const a=[];for(const [t,n] of [['مرغ',21],['خروس',21],['لانه',12],['روباه',7],['تله',3],['مار',2]])for(let i=0;i<n;i++)a.push(t);return shuffle(a)}

export class GameRoom {
  constructor(state){this.state=state;this.sessions=new Map();this.ready=this.load()}
  async load(){this.data=await this.state.storage.get('data')||{rooms:{},online:{},accounts:{},pending:{},queue:[]};this.data.rooms??={};this.data.online??={};this.data.accounts??={};this.data.pending??={};this.data.queue??=[]}
  save(){return this.state.storage.put('data',this.data)}
  send(id,type,data){const ws=this.sessions.get(id);if(ws?.readyState===1)ws.send(JSON.stringify({type,data}))}
  broadcast(type,data){for(const id of this.sessions.keys())this.send(id,type,data)}
  roomBroadcast(r,type,data){if(!r)return;for(const p of r.players||[])this.send(p.id,type,data);for(const id of r.watchers||[])this.send(id,type,data)}
  list(){return Object.values(this.data.online).map(p=>({id:p.id,name:p.name,status:p.status,socketId:p.id,avatar:p.avatar||'🐔'}))}
  updateList(){this.broadcast('playerListUpdate',this.list())}
  account(id,name='بازیکن',avatar='🐔'){return this.data.accounts[id]??(this.data.accounts[id]={accountId:id,username:name,avatar,gamesPlayed:0,wins:0,losses:0,createdAt:Date.now()})}
  player(p){return{id:p.id,name:p.name,accountId:p.accountId||null,avatar:p.avatar||'🐔',hand:[],eggs:0,chicks:0}}
  roomOf(id){for(const [rid,r] of Object.entries(this.data.rooms)){if(r.players?.some(p=>p.id===id))return{roomId:rid,room:r,role:'player'};if(r.watchers?.includes(id))return{roomId:rid,room:r,role:'watcher'}}return null}
  sameRoom(a,b){return Object.values(this.data.rooms).some(r=>r.players?.some(p=>p.id===a)&&r.players?.some(p=>p.id===b))}
  startGame(rid){const r=this.data.rooms[rid];if(!r||r.players.length<2)return false;r.gameStarted=true;r.deck=createDeck();r.discardPile=[];r.eggTokens=18;r.winner=null;r.currentTurn=r.players[0].id;for(const p of r.players){p.hand=[];p.eggs=0;p.chicks=0;for(let i=0;i<4&&r.deck.length;i++)p.hand.push(r.deck.pop());if(this.data.online[p.id])this.data.online[p.id].status='playing'}this.roomBroadcast(r,'gameStarted',{roomId:rid});this.roomBroadcast(r,'gameState',r);return true}
  newRoom(a,b,start=true){let rid;do{rid=Math.random().toString(36).slice(2,8).toUpperCase()}while(this.data.rooms[rid]);this.data.rooms[rid]={host:a.id,players:[this.player(a),this.player(b)],watchers:[],gameStarted:false,deck:createDeck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};if(start)this.startGame(rid);return rid}
  async finish(r){const w=r.players.find(p=>p.chicks>=3);if(!w||r.winner)return;r.winner=w.id;for(const p of r.players){const a=this.account(p.accountId||p.id,p.name,p.avatar);a.gamesPlayed=(a.gamesPlayed||0)+1;if(p.id===w.id)a.wins=(a.wins||0)+1;else a.losses=(a.losses||0)+1;this.send(p.id,'profileData',{profile:a})}}
  async fetch(request){await this.ready;if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket endpoint',{status:426});const pair=new WebSocketPair();const client=pair[0],ws=pair[1];ws.accept();const id=crypto.randomUUID();this.sessions.set(id,ws);this.send(id,'hello',{id});ws.addEventListener('message',e=>this.message(id,e.data));ws.addEventListener('close',()=>this.close(id));return new Response(null,{status:101,webSocket:client})}
  async message(id,raw){await this.ready;let m;try{m=JSON.parse(raw)}catch{return this.send(id,'error','درخواست نامعتبر است')}const t=m?.type,d=m?.data||{};if(!t)return;const online=this.data.online;
    if(t==='loadProfile'){this.send(id,'profileData',{profile:this.data.accounts[d.accountId]||null});return}
    if(t==='saveProfile'){const aid=String(d.accountId||'').trim(),u=String(d.username||'').trim(),av=d.avatar||'🐔';if(!aid||u.length<2||u.length>20)return this.send(id,'profileError','نام کاربری باید بین ۲ تا ۲۰ کاراکتر باشد');if(typeof av!=='string'||av.length>300000)return this.send(id,'profileError','آواتار نامعتبر است یا حجم آن زیاد است');if(Object.values(this.data.accounts).some(a=>a.username===u&&a.accountId!==aid))return this.send(id,'profileError','این نام کاربری قبلاً استفاده شده است');const a=this.account(aid,u,av);a.username=u;a.avatar=av;if(online[id]?.accountId===aid){online[id].name=u;online[id].avatar=av}await this.save();this.send(id,'profileData',{profile:a});this.updateList();return}
    if(t==='registerPlayer'){const aid=String(d.accountId||id),name=String(d.playerName||'بازیکن').trim().slice(0,20)||'بازیکن';if(Object.values(online).some(p=>p.id!==id&&p.name===name))return this.send(id,'registrationError','این نام قبلاً توسط بازیکن دیگری استفاده می‌شود');const a=this.account(aid,name,d.avatar||'🐔');online[id]={id,name:a.username,accountId:aid,avatar:a.avatar||'🐔',status:'ready'};this.send(id,'registrationSuccess',{id,name:a.username});this.updateList();await this.save();return}
    if(t==='getPlayerList'){this.send(id,'playerListUpdate',this.list());return}
    if(t==='getProfile'){const p=online[d.targetId];if(!p)return this.send(id,'profileInfoError','بازیکن یافت نشد');const a=this.account(p.accountId,p.name,p.avatar);this.send(id,'profileInfo',{id:p.id,name:a.username,avatar:a.avatar,gamesPlayed:a.gamesPlayed||0,wins:a.wins||0,losses:a.losses||0});return}
    if(t==='requestGame'){const me=online[id],target=online[d.targetId];if(!me||!target)return this.send(id,'gameRequestError','بازیکن مورد نظر یافت نشد');if(id===d.targetId)return this.send(id,'gameRequestError','نمی‌توانی به خودت درخواست بدهی');this.data.pending[target.id]??=[];this.data.pending[target.id]=this.data.pending[target.id].filter(x=>x.fromId!==id);this.data.pending[target.id].push({fromId:id,fromName:me.name,timestamp:Date.now()});if(me.status==='ready')me.status='requesting';if(target.status==='ready')target.status='requested';this.send(target.id,'gameRequest',{fromId:id,fromName:me.name});this.updateList();await this.save();return}
    if(t==='acceptGame'){const target=online[id],req=online[d.fromId];if(!target||!req)return this.send(id,'gameError','بازیکن یافت نشد');this.data.pending[id]=(this.data.pending[id]||[]).filter(x=>x.fromId!==d.fromId);const current=this.roomOf(id);if(current?.role==='player'){this.send(id,'busyGameChoice',{fromId:req.id,fromName:req.name,roomId:current.roomId,message:`${req.name} می‌خواهد وارد بازی شما شود`});await this.save();return}const rr=this.roomOf(req.id);if(rr?.role==='player')return this.send(id,'gameError','این بازیکن خودش در یک بازی دیگر است');if(rr?.role==='watcher')rr.room.watchers=rr.room.watchers.filter(x=>x!==req.id);target.status='playing';req.status='playing';this.newRoom(req,target,true);this.updateList();await this.save();return}
    if(t==='chooseGameOption'){const target=online[id],req=online[d.fromId],cur=this.roomOf(id);if(!target||!req||!cur||cur.role!=='player'||!['join','watch'].includes(d.option))return;const r=cur.room;if(d.option==='join'){if(!r.players.some(p=>p.id===req.id)){const rr=this.roomOf(req.id);if(rr?.role==='player')return this.send(id,'gameError','این بازیکن خودش در یک بازی دیگر است');if(rr?.role==='watcher')rr.room.watchers=rr.room.watchers.filter(x=>x!==req.id);const np=this.player(req);for(let i=0;i<4&&r.deck.length;i++)np.hand.push(r.deck.pop());r.players.push(np)}req.status='playing';this.send(req.id,'joinExistingGame',{roomId:cur.roomId,room:r,mode:'player'});this.roomBroadcast(r,'roomUpdate',r);this.roomBroadcast(r,'gameState',r)}else{r.watchers??=[];if(!r.watchers.includes(req.id))r.watchers.push(req.id);req.status='watching';this.send(req.id,'joinExistingGame',{roomId:cur.roomId,room:r,mode:'watcher'});this.roomBroadcast(r,'roomUpdate',r);this.roomBroadcast(r,'gameState',r)}this.updateList();await this.save();return}
    if(t==='rejectGame'){const p=online[id],q=online[d.fromId];this.data.pending[id]=(this.data.pending[id]||[]).filter(x=>x.fromId!==d.fromId);if(p&&p.status==='requested')p.status='ready';if(q&&q.status==='requesting')q.status='ready';this.send(d.fromId,'gameRejected',{byName:p?.name||'بازیکن'});this.updateList();await this.save();return}
    if(t==='quickGame'){const p=online[id];if(!p)return this.send(id,'quickGameError','بازیکن یافت نشد');if(p.status!=='ready')return this.send(id,'quickGameError','ابتدا باید آماده باشید');if(!this.data.queue.includes(id))this.data.queue.push(id);p.status='requesting';const q=this.data.queue.filter(x=>online[x]?.status==='requesting');this.data.queue=q;if(q.length>=2){const a=online[q.shift()],b=online[q.shift()];this.data.queue=q;if(a&&b){a.status='playing';b.status='playing';this.newRoom(a,b,true)}}else this.send(id,'quickGameQueued');this.updateList();await this.save();return}
    if(t==='createRoom'){const rid=String(d.roomId||Math.random().toString(36).slice(2,8)).toUpperCase();if(this.data.rooms[rid])return this.send(id,'roomError','اتاق قبلاً وجود دارد');const p=online[id]||{id,name:String(d.playerName||'بازیکن'),accountId:id,avatar:'🐔'};online[id]??=p;this.data.rooms[rid]={host:id,players:[this.player(p)],watchers:[],gameStarted:false,deck:createDeck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};online[id].status='room';this.send(id,'roomCreated',{roomId:rid});this.roomBroadcast(this.data.rooms[rid],'roomUpdate',this.data.rooms[rid]);this.updateList();await this.save();return}
    if(t==='joinRoom'){const rid=String(d.roomId||'').toUpperCase(),r=this.data.rooms[rid];if(!r)return this.send(id,'roomError','اتاق پیدا نشد');if(r.gameStarted)return this.send(id,'roomError','این بازی شروع شده است');if(r.players.length>=2)return this.send(id,'roomError','اتاق پر است');const p=online[id]||{id,name:String(d.playerName||'بازیکن'),accountId:id,avatar:'🐔'};online[id]??=p;online[id].status='room';r.players.push(this.player(p));this.roomBroadcast(r,'roomUpdate',r);this.updateList();await this.save();return}
    if(t==='startGame'){const rid=String(d.roomId||'').toUpperCase(),r=this.data.rooms[rid];if(!r||r.host!==id||r.players.length<2)return;this.startGame(rid);await this.save();return}
    if(t==='getGameState'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(r)this.send(id,'gameState',r);return}
    if(t==='gameAction'){const rid=String(d.roomId||'').toUpperCase(),r=this.data.rooms[rid];if(!r||!r.gameStarted||r.winner)return;const p=r.players.find(x=>x.id===id);if(!p||r.currentTurn!==id)return;const o=r.players.find(x=>x.id===d.data?.target&&x.id!==id)||r.players.find(x=>x.id!==id);let done=false,a=d.action;
      if(a==='lay'){const ix=['مرغ','خروس','لانه'].map(x=>p.hand.indexOf(x));if(ix.every(x=>x>=0)&&r.eggTokens>0){ix.sort((x,y)=>y-x).forEach(x=>p.hand.splice(x,1));p.eggs++;r.eggTokens--;done=true}}
      if(a==='hatch'&&p.eggs>0&&p.hand.filter(x=>x==='مرغ').length>=2){let n=0;for(let i=0;i<p.hand.length&&n<2;i++)if(p.hand[i]==='مرغ'){p.hand.splice(i,1);i--;n++}p.eggs--;p.chicks++;done=true}
      if(a==='draw'&&r.deck.length){p.hand.push(r.deck.pop());done=true}
      if(a==='discard'){const i=p.hand.indexOf(d.data?.card);if(i>=0){r.discardPile.push(p.hand.splice(i,1)[0]);done=true}}
      if(a==='fox'){const i=p.hand.indexOf('روباه');if(i>=0&&o?.eggs>0){p.hand.splice(i,1);if(o.hand.filter(x=>x==='خروس').length>=2){let n=0;for(let j=0;j<o.hand.length&&n<2;j++)if(o.hand[j]==='خروس'){o.hand.splice(j,1);j--;n++}}else{o.eggs--;p.eggs++}done=true}}
      if(a==='snake'){const i=p.hand.indexOf('مار'),n=Math.min(2,Math.max(1,Number(d.data?.count)||1));if(i>=0&&o?.eggs>0){p.hand.splice(i,1);const broken=Math.min(n,o.eggs);o.eggs-=broken;r.eggTokens+=broken;done=true}}
      if(a==='trap'){const i=p.hand.indexOf('تله'),j=o?.hand.indexOf(d.data?.card);if(i>=0&&j>=0){p.hand.splice(i,1);o.hand.splice(j,1);done=true}}
      if(a==='endTurn')done=true;
      if(!done)return;while(p.hand.length<4&&r.deck.length)p.hand.push(r.deck.pop());if(!r.deck.length&&r.discardPile?.length){r.deck=shuffle([...r.discardPile]);r.discardPile=[]}await this.finish(r);if(!r.winner){const i=r.players.findIndex(x=>x.id===r.currentTurn);r.currentTurn=r.players[(i+1)%r.players.length].id}this.roomBroadcast(r,'gameState',r);await this.save();return}
    if(t==='chatMessage'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()],p=r?.players.find(x=>x.id===id);if(!r||!p)return;const msg=String(d.message||'').slice(0,1000);if(!msg)return;this.roomBroadcast(r,'chatMessage',{sender:p.name,message:msg,time:new Date().toLocaleTimeString()});return}
    if(t==='chatMedia'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(!r||!d.content)return;const p=r.players.find(x=>x.id===id),watcher=(r.watchers||[]).includes(id);if(!p&&!watcher)return;const kind=String(d.kind||''),content=String(d.content);if(!['file','gif','sticker'].includes(kind)||content.length>7*1024*1024)return;if(kind==='file'&&Number(d.size||0)>5*1024*1024)return;if(kind==='file'&&/\.(exe|bat|cmd|com|scr|msi|ps1|vbs|js)$/i.test(String(d.name||'')))return;if(kind==='gif'&&d.mime&&d.mime!=='image/gif')return;this.roomBroadcast(r,'chatMedia',{sender:p?.name||online[id]?.name||'تماشاگر',kind,content,name:d.name,mime:d.mime,size:d.size,time:new Date().toLocaleTimeString()});return}
    if(t==='leaveGame'){const cur=this.roomOf(id);if(cur){const r=cur.room;if(cur.role==='player')r.players=r.players.filter(p=>p.id!==id);else r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.data.rooms[cur.roomId];else{if(r.host===id)r.host=r.players[0].id;if(r.currentTurn===id)r.currentTurn=r.players[0].id;this.roomBroadcast(r,'roomUpdate',r);this.roomBroadcast(r,'gameState',r)}}if(online[id])online[id].status='ready';this.data.queue=this.data.queue.filter(x=>x!==id);this.updateList();await this.save();return}
    if(t==='rematchRequest'){const target=online[d.targetId],req=online[id];if(target&&req)this.send(target.id,'rematchRequest',{fromId:id,fromName:req.name,roomId:d.roomId||null});return}
    if(t==='acceptRematch'){const target=online[id],req=online[d.fromId];if(!target||!req)return;const a=this.roomOf(id),b=this.roomOf(req.id);if(a&&b&&a.roomId===b.roomId)delete this.data.rooms[a.roomId];target.status='playing';req.status='playing';const rid=this.newRoom(req,target,true);this.send(req.id,'rematchAccepted',{roomId:rid});this.updateList();await this.save();return}
    if(t==='rejectRematch'){const p=online[id];if(d.fromId)this.send(d.fromId,'rematchRejected',{byName:p?.name||'حریف'});return}
    if(t==='webrtc-offer'||t==='webrtc-answer'||t==='webrtc-ice-candidate'){if(!this.sameRoom(id,d.to))return;const key=t==='webrtc-offer'?'offer':t==='webrtc-answer'?'answer':'candidate';this.send(d.to,t,{from:id,[key]:d[key]});return}
  }
  async close(id){await this.ready;const pending=this.data.pending[id]||[];for(const req of pending){if(this.data.online[req.fromId])this.send(req.fromId,'gameRequestCancelled',{reason:'طرف مقابل قطع شد'});if(this.data.online[req.fromId]?.status==='requesting')this.data.online[req.fromId].status='ready'}delete this.data.pending[id];for(const targetId of Object.keys(this.data.pending)){const arr=this.data.pending[targetId]||[];const kept=arr.filter(x=>x.fromId!==id);if(kept.length!==arr.length){this.data.pending[targetId]=kept;this.send(targetId,'gameRequestCancelled',{reason:'طرف مقابل قطع شد'})}}const cur=this.roomOf(id);if(cur){const r=cur.room;if(cur.role==='player')r.players=r.players.filter(p=>p.id!==id);else r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.data.rooms[cur.roomId];else{if(r.host===id)r.host=r.players[0].id;if(r.currentTurn===id)r.currentTurn=r.players[0].id;this.roomBroadcast(r,'gameState',r);this.roomBroadcast(r,'webrtc-peer-left',{peerId:id})}}delete this.data.online[id];this.data.queue=this.data.queue.filter(x=>x!==id);this.sessions.delete(id);await this.save();this.updateList()}
}

export default {
  async fetch(request,env){
    const u=new URL(request.url);
    if(u.pathname==='/healthz')return new Response('ok',{headers:{'content-type':'text/plain;charset=utf-8'}});
    if(u.pathname==='/socket.io/socket.io.js')return new Response(SOCKET_SHIM,{headers:{'content-type':'application/javascript;charset=utf-8','cache-control':'no-store'}});
    if(u.pathname==='/ws')return env.GAME_ROOM.get(env.GAME_ROOM.idFromName('morgdoni-lobby')).fetch(request);
    const response=await env.ASSETS.fetch(request);
    if(response.status===404)return new Response('Not Found',{status:404});
    const type=response.headers.get('content-type')||'';
    if(u.pathname==='/'||u.pathname==='/index.html'||type.includes('text/html')){
      let html=await response.text();
      if(!/morgdoni-card-fix\.js/i.test(html))html=html.replace(/<\/body>/i,'<script src="/morgdoni-card-fix.js?v=final"></script></body>');
      if(!/socket\.io\/socket\.io\.js/i.test(html))html=html.replace(/<\/head>/i,'<script src="/socket.io/socket.io.js"></script></head>');
      return new Response(html,{status:response.status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
    }
    return response;
  }
};
