const ORIGIN = 'https://raw.githubusercontent.com/saraef1011-alt/index/main/';

const SOCKET_SHIM = `class MorgdoniSocket{constructor(){this.events={};this.id=crypto.randomUUID();const p=location.protocol==='https:'?'wss:':'ws:';this.ws=new WebSocket(p+'//'+location.host+'/ws?room=lobby');this.ws.onopen=()=>this.emitLocal('connect');this.ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m&&m.type)this.emitLocal(m.type,m.data,m)};this.ws.onclose=()=>this.emitLocal('disconnect');this.ws.onerror=e=>this.emitLocal('connect_error',e)}on(e,c){(this.events[e]??=[]).push(c);return this}emit(e,d){const send=()=>this.ws.readyState===1&&this.ws.send(JSON.stringify({type:e,data:d??null}));if(this.ws.readyState===1)send();else this.ws.addEventListener('open',send,{once:true})}emitLocal(e,d,f){for(const c of this.events[e]||[])try{c(d!==undefined?d:f)}catch(x){console.error(x)}}disconnect(){this.ws?.close()}}window.io=()=>new MorgdoniSocket();`;

export class GameRoom {
  constructor(state){this.state=state;this.sessions=new Map();this.ready=this.load()}
  async load(){this.data=await this.state.storage.get('data')||{rooms:{},online:{},profiles:{}}}
  async save(){await this.state.storage.put('data',this.data)}
  send(ws,type,data){if(ws&&ws.readyState===1)ws.send(JSON.stringify({type,data}))}
  broadcastRoom(room,type,data){for(const p of room.players){const ws=this.sessions.get(p.socketId);if(ws)this.send(ws,type,data)}}
  broadcast(type,data){for(const ws of this.sessions.values())this.send(ws,type,data)}
  publicPlayers(){return Object.entries(this.data.online).map(([id,p])=>({id,...p}))}
  deck(){const a=[];for(const [t,n] of [['مرغ',21],['خروس',21],['لانه',12],['روباه',7],['تله',3],['مار',2]])for(let i=0;i<n;i++)a.push(t);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  profile(id,name='بازیکن',avatar='🐔'){return this.data.profiles[id]??(this.data.profiles[id]={accountId:id,username:name,avatar,gamesPlayed:0,wins:0,losses:0})}
  newRoom(players){const id=Math.random().toString(36).slice(2,8).toUpperCase();const r={host:players[0].socketId,players:players.map(p=>({...p,hand:[],eggs:0,chicks:0})),gameStarted:true,deck:this.deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};for(const p of r.players)for(let i=0;i<4;i++)r.deck.length&&r.players.find(x=>x.socketId===p.socketId).hand.push(r.deck.pop());r.currentTurn=r.players[0].socketId;this.data.rooms[id]=r;for(const p of r.players)this.send(this.sessions.get(p.socketId),'gameStarted',{roomId:id});this.broadcastRoom(r,'gameState',r);return id}
  finish(r){const w=r.players.find(p=>p.chicks>=3);if(!w||r.winner)return;if(r.winner=w.socketId, this.data.profiles[w.accountId])this.data.profiles[w.accountId].wins++;for(const p of r.players){const q=this.data.profiles[p.accountId];if(q){q.gamesPlayed++;if(p.socketId!==w.socketId)q.losses++}}}
  async fetch(request){await this.ready;if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket endpoint',{status:426});const pair=new WebSocketPair(),client=pair[0],ws=pair[1];ws.accept();const sid=crypto.randomUUID();this.sessions.set(sid,ws);ws.addEventListener('message',e=>this.onMessage(sid,e.data));ws.addEventListener('close',()=>this.onClose(sid));return new Response(null,{status:101,webSocket:client})}
  async onMessage(sid,raw){await this.ready;let m;try{m=JSON.parse(raw)}catch{return this.send(this.sessions.get(sid),'error','درخواست نامعتبر')};const d=m.data||{};const ws=this.sessions.get(sid);
    if(m.type==='loadProfile'){this.send(ws,'profileData',{profile:this.data.profiles[d.accountId]||null});return}
    if(m.type==='saveProfile'){if(!d.accountId||!d.username||String(d.username).trim().length<2)return this.send(ws,'profileError','نام کاربری معتبر نیست');const p=this.profile(d.accountId,String(d.username).trim(),d.avatar||'🐔');p.username=String(d.username).trim();p.avatar=d.avatar||p.avatar;await this.save();this.send(ws,'profileData',{profile:p});return}
    if(m.type==='registerPlayer'){const p=this.profile(d.accountId||sid,d.playerName||'بازیکن',d.avatar||'🐔');this.data.online[sid]={name:p.username,accountId:p.accountId,avatar:p.avatar,status:'ready'};this.send(ws,'registrationSuccess',{id:sid,name:p.username});this.broadcast('playerListUpdate',this.publicPlayers());await this.save();return}
    if(m.type==='getProfile'){const o=this.data.online[d.targetId];if(!o)return this.send(ws,'profileInfoError','بازیکن آنلاین نیست');const p=this.profile(o.accountId,o.name,o.avatar);return this.send(ws,'profileInfo',{name:p.username,avatar:p.avatar,gamesPlayed:p.gamesPlayed,wins:p.wins,losses:p.losses})}
    if(m.type==='createRoom'){const roomId=String(d.roomId||Math.random().toString(36).slice(2,8)).toUpperCase();if(this.data.rooms[roomId])return this.send(ws,'roomError','اتاق قبلاً وجود دارد');const o=this.data.online[sid]||{accountId:sid,name:d.playerName||'بازیکن',avatar:'🐔'};this.data.rooms[roomId]={host:sid,players:[{socketId:sid,id:sid,name:d.playerName||o.name,accountId:o.accountId,avatar:o.avatar,hand:[],eggs:0,chicks:0}],gameStarted:false,deck:this.deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};this.data.online[sid]&&(this.data.online[sid].status='room');await this.save();this.send(ws,'roomCreated',{roomId});this.broadcastRoom(this.data.rooms[roomId],'roomUpdate',this.data.rooms[roomId]);this.broadcast('playerListUpdate',this.publicPlayers());return}
    if(m.type==='joinRoom'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(!r)return this.send(ws,'roomError','اتاق پیدا نشد');if(r.players.length>=2)return this.send(ws,'roomError','اتاق پر است');const o=this.data.online[sid]||{accountId:sid,name:d.playerName||'بازیکن',avatar:'🐔'};r.players.push({socketId:sid,id:sid,name:d.playerName||o.name,accountId:o.accountId,avatar:o.avatar,hand:[],eggs:0,chicks:0});this.data.online[sid]&&(this.data.online[sid].status='room');await this.save();this.broadcastRoom(r,'roomUpdate',r);return}
    if(m.type==='startGame'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(!r||r.host!==sid||r.players.length<2)return;r.gameStarted=true;r.deck=this.deck();r.players.forEach(p=>{p.hand=[];p.eggs=0;p.chicks=0;for(let i=0;i<4;i++)r.deck.length&&p.hand.push(r.deck.pop())});r.currentTurn=r.players[0].socketId;await this.save();this.broadcastRoom(r,'gameState',r);return}
    if(m.type==='getGameState'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(r)this.send(ws,'gameState',r);return}
    if(m.type==='quickGame'){const me=this.data.online[sid];const other=Object.entries(this.data.online).find(([id,p])=>id!==sid&&p.status==='ready');if(!me)return this.send(ws,'quickGameError','ابتدا وارد لابی شو');if(!other)return this.send(ws,'quickGameError','منتظر بازیکن دیگری بمان...');return this.newRoom([{socketId:sid,name:me.name,accountId:me.accountId,avatar:me.avatar},{socketId:other[0],name:other[1].name,accountId:other[1].accountId,avatar:other[1].avatar}])}
    if(m.type==='gameAction'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()];if(!r||!r.gameStarted||r.winner)return;const p=r.players.find(x=>x.socketId===sid);if(!p||r.currentTurn!==sid)return;const o=r.players.find(x=>x.socketId===d.data?.target&&x.socketId!==sid)||r.players.find(x=>x.socketId!==sid);let done=false;const action=d.action;
      if(action==='lay'){const ids=['مرغ','خروس','لانه'].map(c=>p.hand.indexOf(c));if(ids.every(i=>i>=0)&&r.eggTokens){ids.sort((a,b)=>b-a).forEach(i=>p.hand.splice(i,1));p.eggs++;r.eggTokens--;done=true}}
      if(action==='hatch'&&p.eggs>0&&p.hand.filter(x=>x==='مرغ').length>=2){let n=0;for(let i=0;i<p.hand.length&&n<2;i++)if(p.hand[i]==='مرغ'){p.hand.splice(i,1);i--;n++}p.eggs--;p.chicks++;done=true}
      if(action==='draw'&&r.deck.length){p.hand.push(r.deck.pop());done=true}
      if(action==='discard'){const i=p.hand.indexOf(d.data?.card);if(i>=0){r.discardPile.push(p.hand.splice(i,1)[0]);done=true}}
      if(action==='fox'){const i=p.hand.indexOf('روباه');if(i>=0&&o?.eggs>0){p.hand.splice(i,1);o.eggs--;p.eggs++;done=true}}
      if(action==='snake'){const i=p.hand.indexOf('مار');const n=Math.min(2,Math.max(1,Number(d.data?.count)||1));if(i>=0&&o?.eggs>0){p.hand.splice(i,1);const b=Math.min(n,o.eggs);o.eggs-=b;r.eggTokens+=b;done=true}}
      if(action==='trap'){const i=p.hand.indexOf('تله');const j=o?.hand.indexOf(d.data?.card);if(i>=0&&j>=0){p.hand.splice(i,1);o.hand.splice(j,1);done=true}}
      if(action==='endTurn')done=true;if(!done)return;while(p.hand.length<4&&r.deck.length)p.hand.push(r.deck.pop());this.finish(r);if(!r.winner){const i=r.players.findIndex(x=>x.socketId===r.currentTurn);r.currentTurn=r.players[(i+1)%r.players.length].socketId}await this.save();this.broadcastRoom(r,'gameState',r);return}
    if(m.type==='chatMessage'){const r=this.data.rooms[String(d.roomId||'').toUpperCase()],p=r?.players.find(x=>x.socketId===sid);if(p)this.broadcastRoom(r,'chatMessage',{sender:p.name,message:d.message,time:new Date().toLocaleTimeString()});return}
    if(m.type==='leaveGame'){for(const [rid,r] of Object.entries(this.data.rooms)){const i=r.players.findIndex(p=>p.socketId===sid);if(i>=0){r.players.splice(i,1);if(!r.players.length)delete this.data.rooms[rid];else{r.host=r.players[0].socketId;r.currentTurn=r.players[0].socketId;this.broadcastRoom(r,'roomUpdate',r)}}}if(this.data.online[sid])this.data.online[sid].status='ready';await this.save();this.broadcast('playerListUpdate',this.publicPlayers());return}
  }
  async onClose(sid){await this.ready;for(const [rid,r] of Object.entries(this.data.rooms)){const i=r.players.findIndex(p=>p.socketId===sid);if(i>=0){r.players.splice(i,1);if(!r.players.length)delete this.data.rooms[rid];else{r.host=r.players[0].socketId;r.currentTurn=r.players[0].socketId;this.broadcastRoom(r,'roomUpdate',r)}}}delete this.data.online[sid];this.sessions.delete(sid);await this.save();this.broadcast('playerListUpdate',this.publicPlayers())}
}

export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/healthz')return new Response('ok');if(u.pathname==='/socket.io/socket.io.js')return new Response(SOCKET_SHIM,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});if(u.pathname==='/ws'){return env.GAME_ROOM.get(env.GAME_ROOM.idFromName('morgdoni-lobby')).fetch(request)}if(u.pathname==='/'){const r=await fetch(ORIGIN+'index.html');let html=await r.text();html=html.replace(/<script[^>]+src=["']\/socket\.io\/socket\.io\.js["'][^>]*><\/script>/i,'<script src="/socket.io/socket.io.js"></script>');return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}if(u.pathname==='/morgdoni-fix.js'||u.pathname==='/cloudflare-socket.js'){return fetch(ORIGIN+u.pathname.slice(1))}return fetch(ORIGIN+u.pathname.slice(1))}};
