const SHIM=`class MorgdoniSocket{constructor(){this.events={};this.id=crypto.randomUUID();const p=location.protocol==='https:'?'wss:':'ws:';this.ws=new WebSocket(p+'//'+location.host+'/ws');this.ws.onopen=()=>this.emitLocal('connect');this.ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m?.type)this.emitLocal(m.type,m.data)}catch{}};this.ws.onclose=()=>this.emitLocal('disconnect');this.ws.onerror=e=>this.emitLocal('connect_error',e)}on(e,c){(this.events[e]??=[]).push(c);return this}emit(e,d){const m=JSON.stringify({type:e,data:d??null});if(this.ws.readyState===1)this.ws.send(m);else this.ws.addEventListener('open',()=>this.ws.send(m),{once:true})}emitLocal(e,d){for(const c of this.events[e]||[])try{c(d)}catch(x){console.error(x)}}disconnect(){this.ws?.close()}}window.io=()=>new MorgdoniSocket();`;
const NAMES={Hen:'Hen.png',Rooster:'Rooster.png',Nest:'Nest.png',Fox:'Fox.png',Snake:'Snake.png',Trap:'Trap.png',hen:'Hen.png',rooster:'Rooster.png',nest:'Nest.png',fox:'Fox.png',snake:'Snake.png',trap:'Trap.png'};
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(){let a=[];for(const [x,n] of [['مرغ',21],['خروس',21],['لانه',12],['روباه',7],['تله',3],['مار',2]])for(let i=0;i<n;i++)a.push(x);return shuffle(a)}
export class GameRoom{
 constructor(state){this.state=state;this.s=new Map;this.ready=this.load()}
 async load(){this.d=await this.state.storage.get('data')||{rooms:{},online:{},accounts:{},pending:{},queue:[]};this.d.rooms??={};this.d.online??={};this.d.accounts??={};this.d.pending??={};this.d.queue??=[]}
 save(){return this.state.storage.put('data',this.d)}
 send(id,type,data){const w=this.s.get(id);if(w?.readyState===1)w.send(JSON.stringify({type,data}))}
 broadcast(type,data){for(const id of this.s.keys())this.send(id,type,data)}
 roomSend(r,type,data){if(!r)return;for(const p of r.players||[])this.send(p.id,type,data);for(const id of r.watchers||[])this.send(id,type,data)}
 list(){return Object.values(this.d.online).map(p=>({id:p.id,name:p.name,status:p.status,socketId:p.id,avatar:p.avatar||'🐔'}))}
 updateList(){this.broadcast('playerListUpdate',this.list())}
 account(id,name='بازیکن',avatar='🐔'){return this.d.accounts[id]??(this.d.accounts[id]={accountId:id,username:name,avatar,gamesPlayed:0,wins:0,losses:0,createdAt:Date.now()})}
 roomOf(id){for(const [rid,r] of Object.entries(this.d.rooms)){if(r.players?.some(p=>p.id===id))return{rid,r,role:'player'};if(r.watchers?.includes(id))return{rid,r,role:'watcher'}}return null}
 sameRoom(a,b){return Object.values(this.d.rooms).some(r=>r.players?.some(p=>p.id===a)&&r.players?.some(p=>p.id===b))}
 newRoom(a,b,start=true){let rid=Math.random().toString(36).slice(2,8).toUpperCase();this.d.rooms[rid]={host:a.id,players:[this.player(a),this.player(b)],watchers:[],gameStarted:false,deck:deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};if(start)this.start(rid);return rid}
 player(p){return{id:p.id,name:p.name,accountId:p.accountId||null,avatar:p.avatar||'🐔',hand:[],eggs:0,chicks:0}}
 start(rid){let r=this.d.rooms[rid];if(!r||r.players.length<2)return;if(r.gameStarted&&r.winner)return;r.gameStarted=true;r.deck=deck();r.discardPile=[];r.eggTokens=18;r.winner=null;r.currentTurn=r.players[0].id;for(const p of r.players){p.hand=[];p.eggs=0;p.chicks=0;for(let i=0;i<4;i++)if(r.deck.length)p.hand.push(r.deck.pop());if(this.d.online[p.id])this.d.online[p.id].status='playing'}this.roomSend(r,'gameStarted',{roomId:rid});this.roomSend(r,'gameState',r)}
 async result(r){let w=r.players.find(p=>p.chicks>=3);if(!w||r.winner)return;r.winner=w.id;for(const p of r.players){let a=this.account(p.accountId||p.id,p.name,p.avatar);a.gamesPlayed=(a.gamesPlayed||0)+1;if(p.id===w.id)a.wins=(a.wins||0)+1;else a.losses=(a.losses||0)+1;this.send(p.id,'profileData',{profile:a})}}
 async fetch(req){await this.ready;if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket endpoint',{status:426});let pair=new WebSocketPair(),ws=pair[1],client=pair[0],id=crypto.randomUUID();ws.accept();this.s.set(id,ws);this.send(id,'hello',{id});ws.addEventListener('message',e=>this.msg(id,e.data));ws.addEventListener('close',()=>this.close(id));return new Response(null,{status:101,webSocket:client})}
 async msg(id,raw){await this.ready;let m;try{m=JSON.parse(raw)}catch{return this.send(id,'error','درخواست نامعتبر')};let d=m.data||{},t=m.type,w=this.s.get(id);if(!w)return;
  if(t==='loadProfile'){this.send(id,'profileData',{profile:this.d.accounts[d.accountId]||null});return}
  if(t==='saveProfile'){let aid=String(d.accountId||''),u=String(d.username||'').trim(),av=d.avatar||'🐔';if(!aid||u.length<2||u.length>20)return this.send(id,'profileError','نام کاربری باید بین ۲ تا ۲۰ کاراکتر باشد');if(typeof av!=='string'||av.length>300000)return this.send(id,'profileError','آواتار نامعتبر است یا حجم آن زیاد است');if(Object.values(this.d.accounts).some(a=>a.username===u&&a.accountId!==aid))return this.send(id,'profileError','این نام کاربری قبلاً استفاده شده است');let a=this.account(aid,u,av);a.username=u;a.avatar=av;if(this.d.online[id]?.accountId===aid){this.d.online[id].name=u;this.d.online[id].avatar=av}await this.save();this.send(id,'profileData',{profile:a});this.updateList();return}
  if(t==='registerPlayer'){let aid=d.accountId||id,name=String(d.playerName||'بازیکن').trim().slice(0,20)||'بازیکن';if(Object.values(this.d.online).some(p=>p.id!==id&&p.name===name))return this.send(id,'registrationError','این نام قبلاً توسط بازیکن دیگری استفاده می‌شود');let a=this.account(aid,name,d.avatar||'🐔');this.d.online[id]={id,name:a.username,accountId:aid,avatar:a.avatar||'🐔',status:'ready'};this.send(id,'registrationSuccess',{id,name:a.username});this.updateList();await this.save();return}
  if(t==='getPlayerList'){this.send(id,'playerListUpdate',this.list());return}
  if(t==='getProfile'){let p=this.d.online[d.targetId];if(!p)return this.send(id,'profileInfoError','بازیکن یافت نشد');let a=this.account(p.accountId,p.name,p.avatar);return this.send(id,'profileInfo',{id:p.id,name:a.username,avatar:a.avatar,gamesPlayed:a.gamesPlayed||0,wins:a.wins||0,losses:a.losses||0})}
  if(t==='requestGame'){let me=this.d.online[id],to=this.d.online[d.targetId];if(!me||!to)return this.send(id,'gameRequestError','بازیکن مورد نظر یافت نشد');if(id===d.targetId)return this.send(id,'gameRequestError','نمی‌توانی به خودت درخواست بدهی');this.d.pending[to.id]??=[];this.d.pending[to.id]=this.d.pending[to.id].filter(x=>x.fromId!==id);this.d.pending[to.id].push({fromId:id,fromName:me.name,timestamp:Date.now()});if(me.status==='ready')me.status='requesting';if(to.status==='ready')to.status='requested';this.send(to.id,'gameRequest',{fromId:id,fromName:me.name});this.updateList();await this.save();return}
  if(t==='acceptGame'){let target=this.d.online[id],req=this.d.online[d.fromId];if(!target||!req)return this.send(id,'gameError','بازیکن یافت نشد');this.d.pending[id]=(this.d.pending[id]||[]).filter(x=>x.fromId!==d.fromId);let current=this.roomOf(id);if(current?.role==='player'){this.send(id,'busyGameChoice',{fromId:d.fromId,fromName:req.name,roomId:current.rid,message:`${req.name} می‌خواهد وارد بازی شما شود`});await this.save();return}let rr=this.roomOf(req.id);if(rr?.role==='player')return this.send(id,'gameError','این بازیکن خودش در یک بازی دیگر است');if(rr?.role==='watcher')rr.r.watchers=rr.r.watchers.filter(x=>x!==req.id);target.status='playing';req.status='playing';let rid=this.newRoom(req,target,true);this.updateList();await this.save();return}
  if(t==='chooseGameOption'){let target=this.d.online[id],req=this.d.online[d.fromId],cur=this.roomOf(id);if(!target||!req||!cur||!['join','watch'].includes(d.option))return;let r=cur.r;if(d.option==='join'){if(!r.players.some(p=>p.id===req.id)){let rr=this.roomOf(req.id);if(rr?.role==='player')return this.send(id,'gameError','این بازیکن خودش در یک بازی دیگر است');if(rr?.role==='watcher')rr.r.watchers=rr.r.watchers.filter(x=>x!==req.id);let np=this.player(req);for(let i=0;i<4&&r.deck.length;i++)np.hand.push(r.deck.pop());r.players.push(np)}req.status='playing';this.send(req.id,'joinExistingGame',{roomId:cur.rid,room:r,mode:'player'});this.roomSend(r,'roomUpdate',r);this.roomSend(r,'gameState',r)}else{r.watchers??=[];if(!r.watchers.includes(req.id))r.watchers.push(req.id);req.status='watching';this.send(req.id,'joinExistingGame',{roomId:cur.rid,room:r,mode:'watcher'});this.roomSend(r,'roomUpdate',r);this.roomSend(r,'gameState',r)}this.updateList();await this.save();return}
  if(t==='rejectGame'){let p=this.d.online[id],q=this.d.online[d.fromId];this.d.pending[id]=(this.d.pending[id]||[]).filter(x=>x.fromId!==d.fromId);if(p&&p.status==='requested')p.status='ready';if(q&&q.status==='requesting')q.status='ready';this.send(d.fromId,'gameRejected',{byName:p?.name||'بازیکن'});this.updateList();await this.save();return}
  if(t==='quickGame'){let p=this.d.online[id];if(!p)return this.send(id,'quickGameError','بازیکن یافت نشد');if(p.status!=='ready')return this.send(id,'quickGameError','ابتدا باید آماده باشید');if(!this.d.queue.includes(id))this.d.queue.push(id);p.status='requesting';let q=this.d.queue.filter(x=>this.d.online[x]?.status==='requesting');this.d.queue=q;if(q.length>=2){let a=this.d.online[q.shift()],b=this.d.online[q.shift()];this.d.queue=q;if(a&&b){a.status='playing';b.status='playing';this.newRoom(a,b,true)}}else this.send(id,'quickGameQueued');this.updateList();await this.save();return}
  if(t==='createRoom'){let rid=String(d.roomId||Math.random().toString(36).slice(2,8)).toUpperCase();if(this.d.rooms[rid])return this.send(id,'roomError','اتاق قبلاً وجود دارد');let p=this.d.online[id]||{id,name:String(d.playerName||'بازیکن'),accountId:id,avatar:'🐔'};this.d.online[id]??=p;this.d.rooms[rid]={host:id,players:[this.player(p)],watchers:[],gameStarted:false,deck:deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[]};this.d.online[id].status='room';this.send(id,'roomCreated',{roomId:rid});this.roomSend(this.d.rooms[rid],'roomUpdate',this.d.rooms[rid]);this.updateList();await this.save();return}
  if(t==='joinRoom'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(!r)return this.send(id,'roomError','اتاق پیدا نشد');if(r.gameStarted)return this.send(id,'roomError','این بازی شروع شده است');if(r.players.length>=2)return this.send(id,'roomError','اتاق پر است');let p=this.d.online[id]||{id,name:String(d.playerName||'بازیکن'),accountId:id,avatar:'🐔'};this.d.online[id]??=p;this.d.online[id].status='room';r.players.push(this.player(p));this.roomSend(r,'roomUpdate',r);this.updateList();await this.save();return}
  if(t==='startGame'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(!r||r.host!==id||r.players.length<2)return;this.start(rid);await this.save();return}
  if(t==='getGameState'){let r=this.d.rooms[String(d.roomId||'').toUpperCase()];if(r)this.send(id,'gameState',r);return}
  if(t==='gameAction'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(!r||!r.gameStarted||r.winner)return;let p=r.players.find(x=>x.id===id);if(!p||r.currentTurn!==id)return;let o=r.players.find(x=>x.id===d.data?.target&&x.id!==id)||r.players.find(x=>x.id!==id),done=false,a=d.action;
    if(a==='lay'){let ix=['مرغ','خروس','لانه'].map(x=>p.hand.indexOf(x));if(ix.every(x=>x>=0)&&r.eggTokens>0){ix.sort((x,y)=>y-x).forEach(x=>p.hand.splice(x,1));p.eggs++;r.eggTokens--;done=true}}
    if(a==='hatch'&&p.eggs>0&&p.hand.filter(x=>x==='مرغ').length>=2){let n=0;for(let i=0;i<p.hand.length&&n<2;i++)if(p.hand[i]==='مرغ'){p.hand.splice(i,1);i--;n++}p.eggs--;p.chicks++;done=true}
    if(a==='draw'&&r.deck.length){p.hand.push(r.deck.pop());done=true}
    if(a==='discard'){let i=p.hand.indexOf(d.data?.card);if(i>=0){r.discardPile.push(p.hand.splice(i,1)[0]);done=true}}
    if(a==='fox'){let i=p.hand.indexOf('روباه');if(i>=0&&o?.eggs>0){p.hand.splice(i,1);if(o.hand.filter(x=>x==='خروس').length>=2){let n=0;for(let j=0;j<o.hand.length&&n<2;j++)if(o.hand[j]==='خروس'){o.hand.splice(j,1);j--;n++}}else{o.eggs--;p.eggs++}done=true}}
    if(a==='snake'){let i=p.hand.indexOf('مار'),n=Math.min(2,Math.max(1,Number(d.data?.count)||1));if(i>=0&&o?.eggs>0){p.hand.splice(i,1);let b=Math.min(n,o.eggs);o.eggs-=b;r.eggTokens+=b;done=true}}
    if(a==='trap'){let i=p.hand.indexOf('تله'),card=d.data?.card,j=o?.hand.indexOf(card);if(i>=0&&j>=0&&['مرغ','خروس','روباه','مار'].includes(card)){p.hand.splice(i,1);o.hand.splice(j,1);done=true}}
    if(a==='endTurn')done=true;if(!done)return;while(p.hand.length<4){if(r.deck.length)p.hand.push(r.deck.pop());else if(r.discardPile.length)r.deck=shuffle(r.discardPile.splice(0));else break}await this.result(r);if(!r.winner){let i=r.players.findIndex(x=>x.id===r.currentTurn);r.currentTurn=r.players[(i+1)%r.players.length].id}this.roomSend(r,'gameState',r);await this.save();return}
  if(t==='chatMessage'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(!r)return;let p=r.players.find(x=>x.id===id);if(!p&&!(r.watchers||[]).includes(id))return;let msg=String(d.message||'').slice(0,2000);if(msg)this.roomSend(r,'chatMessage',{sender:p?.name||this.d.online[id]?.name||'تماشاگر',message:msg,time:new Date().toLocaleTimeString()});return}
  if(t==='chatMedia'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(!r||!d.content)return;let p=r.players.find(x=>x.id===id);if(!p&&!(r.watchers||[]).includes(id))return;let kind=String(d.kind||''),content=String(d.content||'');if(!['file','gif','sticker'].includes(kind)||content.length>7*1024*1024)return;if(kind==='file'&&Number(d.size||0)>5*1024*1024)return;let name=String(d.name||'file').replace(/[<>:"/\\|?*]/g,'_').slice(0,120);if(/\.(exe|bat|cmd|com|scr|msi|ps1|vbs|js)$/i.test(name))return;if(kind==='gif'&&d.mime&&d.mime!=='image/gif')return;this.roomSend(r,'chatMedia',{sender:p?.name||this.d.online[id]?.name||'تماشاگر',kind,content,name,mime:d.mime,size:d.size,time:new Date().toLocaleTimeString()});return}
  if(['webrtc-offer','webrtc-answer','webrtc-ice-candidate'].includes(t)){if(!this.sameRoom(id,d.to))return;let key=t==='webrtc-offer'?'offer':t==='webrtc-answer'?'answer':'candidate';this.send(d.to,t,{from:id,[key]:d[key]});return}
  if(t==='leaveGame'){let rid=String(d.roomId||'').toUpperCase(),r=this.d.rooms[rid];if(r){r.players=r.players.filter(p=>p.id!==id);r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.d.rooms[rid];else{r.host=r.players[0].id;if(r.gameStarted&&!r.winner)r.currentTurn=r.players[0].id;this.roomSend(r,'gameState',r);this.roomSend(r,'roomUpdate',r);this.roomSend(r,'webrtc-peer-left',{peerId:id})}}this.d.queue=this.d.queue.filter(x=>x!==id);if(this.d.online[id])this.d.online[id].status='ready';this.updateList();await this.save();return}
  if(t==='rematchRequest'){let to=this.d.online[d.targetId],me=this.d.online[id];if(to&&me)this.send(to.id,'rematchRequest',{fromId:id,fromName:me.name,roomId:d.roomId||null});return}
  if(t==='acceptRematch'){let a=this.d.online[id],b=this.d.online[d.fromId];if(!a||!b)return;let ra=this.roomOf(id),rb=this.roomOf(d.fromId);if(ra&&rb&&ra.rid===rb.rid){let r=ra.r;r.players=r.players.filter(p=>p.id!==id&&p.id!==d.fromId);r.watchers=(r.watchers||[]).filter(x=>x!==id&&x!==d.fromId);if(!r.players.length)delete this.d.rooms[ra.rid]}a.status='playing';b.status='playing';let rid=this.newRoom(b,a,true);this.send(b.id,'rematchAccepted',{roomId:rid});this.updateList();await this.save();return}
  if(t==='rejectRematch'){let p=this.d.online[id];if(d.fromId)this.send(d.fromId,'rematchRejected',{byName:p?.name||'حریف'});return}
 }
 async close(id){await this.ready;for(const rid of Object.keys(this.d.rooms)){let r=this.d.rooms[rid];if(r.players.some(p=>p.id===id)||(r.watchers||[]).includes(id)){r.players=r.players.filter(p=>p.id!==id);r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.d.rooms[rid];else{r.host=r.players[0].id;if(r.gameStarted&&!r.winner)r.currentTurn=r.players[0].id;this.roomSend(r,'gameState',r);this.roomSend(r,'webrtc-peer-left',{peerId:id})}}}delete this.d.online[id];this.d.queue=this.d.queue.filter(x=>x!==id);this.s.delete(id);await this.save();this.updateList()}
}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==='/healthz')return new Response('ok');if(u.pathname==='/socket.io/socket.io.js')return new Response(SHIM,{headers:{'content-type':'application/javascript;charset=utf-8','cache-control':'no-store'}});if(u.pathname==='/ws')return env.GAME_ROOM.get(env.GAME_ROOM.idFromName('morgdoni-global-room')).fetch(req);
  // سازگاری با مسیر کارت‌های پروژه: index.html از /assets/cards استفاده می‌کند، ولی فایل‌های GitHub داخل /cards هستند و نامشان با حرف بزرگ شروع می‌شود.
  if(u.pathname.startsWith('/assets/cards/')){const raw=u.pathname.split('/').pop();const key=raw.replace(/\.png$/i,'');const file=NAMES[key]||raw;return env.ASSETS.fetch(new Request(new URL('/cards/'+file,req.url),req))}
  // GIF چت پروژه
  if(u.pathname==='/assets/chat/chicken.gif')return env.ASSETS.fetch(new Request(new URL('/assets/chat/chicken.gif',req.url),req));
  return env.ASSETS.fetch(req);
}};
